
# data.py — airports mapping & small helpers
# Note: This is your original mapping, trimmed a bit. You can extend as needed.

leds =[
{"led":0,"code":"EGHC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Land's End Airport"},
{"led":1,"code":"EGDR","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RNAS Culdrose"},
{"led":2,"code":"EGHQ","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Cornwall Airport Newquay"},
{"led":3,"code":"EGTE","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Exeter International Airport"},
{"led":4,"code":"EGOP","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Pembrey Sands"},
{"led":5,"code":"EGSY","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"St. Athan"},
{"led":6,"code":"EGFF","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Cardiff International Airport"},
{"led":7,"code":"EGGD","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Bristol Airport"},
{"led":8,"code":"EGDY","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RNAS Yeovilton"},
{"led":9,"code":"EGHH","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Bournemouth Airport"},
{"led":10,"code":"EGHI","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Southampton Airport"},
{"led":11,"code":"EGDM","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"MoD Boscombe Down Airport"},
{"led":12,"code":"EGVP","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Middle Wallop Airfield"},
{"led":13,"code":"EGVO","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Odiham"},
{"led":14,"code":"EGLF","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Farnborough Airport"},
{"led":15,"code":"EGKK","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"London Gatwick Airport"},
{"led":16,"code":"EGKA","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Brighton City Airport"},
{"led":17,"code":"EGMD","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Lydd Airport"},
{"led":18,"code":"EGMC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Southend Airport"},
{"led":19,"code":"EGLC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"London City Airport"},
{"led":20,"code":"EGKB","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"London Biggin Hill Airport"},
{"led":21,"code":"EGLL","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"London Heathrow Airport"},
{"led":22,"code":"EGWU","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Northolt"},
{"led":23,"code":"EGUB","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Benson"},
{"led":24,"code":"EGVA","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Fairford"},
{"led":25,"code":"EGBJ","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Gloucestershire Airport"},
{"led":26,"code":"EGVN","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Brize Norton"},
{"led":27,"code":"EGTK","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Oxford (Kidlington) Airport"},
{"led":28,"code":"EGTC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Cranfield Airport"},
{"led":29,"code":"EGGW","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"London Luton Airport"},
{"led":30,"code":"EGSS","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"London Stansted Airport"},
{"led":31,"code":"EGSC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Cambridge Airport"},
{"led":32,"code":"EGUN","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Mildenhall"},
{"led":33,"code":"EGUL","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Lakenheath"},
{"led":34,"code":"EGUW","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Wattisham Airfield"},
{"led":35,"code":"EGSH","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Norwich Airport"},
{"led":36,"code":"EGYM","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Marham"},
{"led":37,"code":"EGYH","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Holbeach"},
{"led":38,"code":"EGXC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Coningsby"},
{"led":39,"code":"EGXS","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Donna"},
{"led":40,"code":"EGNJ","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Humberside Airport"},
{"led":41,"code":"EGXW","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Waddington"},
{"led":42,"code":"EGYD","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Cranwell"},
{"led":43,"code":"EGYE","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Barkston Heath"},
{"led":44,"code":"EGXT","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Wittering"},
{"led":45,"code":"EGNX","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"East Midlands Airport"},
{"led":46,"code":"EGBB","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Birmingham International Airport"},
{"led":47,"code":"EGWC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"DCAE Cosford Air Base"},
{"led":48,"code":"EGOS","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Shawbury"},
{"led":49,"code":"EGNR","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Hawarden Airport"},
{"led":50,"code":"EGGP","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Liverpool John Lennon Airport"},
{"led":51,"code":"EGCK","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Caernarfon Airport"},
{"led":53,"code":"EIWF","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Waterford"},
{"led":54,"code":"EIME","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Baldonnel"},
{"led":55,"code":"EIDW","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Dublin"},
{"led":56,"code":"EGNS","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Isle of Man"},
{"led":57,"code":"EGOV","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Anglesey Airport"},
{"led":58,"code":"EGOW","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Woodvale"},
{"led":59,"code":"EGNH","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Blackpool International Airport"},
{"led":60,"code":"EGNO","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Warton Aerodrome"},
{"led":61,"code":"EGCC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Manchester Airport"},
{"led":62,"code":"EGSY","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Yorkshire"},
{"led":63,"code":"EGNM","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Leeds Bradford Airport"},
{"led":64,"code":"EGXV","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Leconfield"},
{"led":65,"code":"EGXZ","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Topcliffe"},
{"led":66,"code":"EGXE","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Leeming Air Base"},
{"led":67,"code":"EGNV","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Teesside International Airport"},
{"led":68,"code":"EGNT","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Newcastle Airport"},
{"led":69,"code":"EGOM","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Spadeadam"},
{"led":70,"code":"EGQM","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Boulmer"},
{"led":71,"code":"EGQL","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Leuchars Station Airfield"},
{"led":72,"code":"EGPN","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Dundee Airport"},
{"led":73,"code":"EGPD","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Aberdeen Dyce Airport"},
{"led":74,"code":"EGQS","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Lossiemouth"},
{"led":75,"code":"EGPC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Wick Airport"},
{"led":76,"code":"EGQA","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Tain Range"},
{"led":77,"code":"EGQK","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"RAF Kinloss"},
{"led":78,"code":"EGPE","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Inverness Airport"},
{"led":79,"code":"EGPO","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Stornoway Airport"},
{"led":80,"code":"EGPL","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Benbecula Airport"},
{"led":81,"code":"EGPU","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Tiree Airport"},
{"led":82,"code":"EGEO","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Oban Airport"},
{"led":83,"code":"EGPI","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Islay Airport"},
{"led":84,"code":"EGAE","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"City of Derry Airport"},
{"led":85,"code":"EGAA","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Belfast International Airport"},
{"led":86,"code":"EGAC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"George Best Belfast City Airport"},
{"led":87,"code":"EGEC","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Campbeltown Airport"},
{"led":88,"code":"EGPK","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Glasgow Prestwick Airport"},
{"led":89,"code":"EGPF","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Glasgow International Airport"},
{"led":90,"code":"EGPH","raw":None,"windSpeed":None,"windGust":None,"windGustSpeed":None,"lightning":None,"flightCategory":None,"airport":"Edinburgh Airport"}
]

def find(lst, key, value):
    for i, d in enumerate(lst):
        if d.get(key) == value:
            return i
    return -1
